iOS: Updated project for Jenkins.
- MPfm.MVP doesn't build in Jenkins because of this error:
InitializationService.cs(328,13) : error CS0103: The name
`MonoSQLiteGateway' does not exist in the current contex

- Created static method in DatabaseFacade to try to fix this error.